"""SPIKES public API. Optional analysis modules are imported on first use."""

from importlib import import_module as _import_module
from .version import ENGINE_VERSION

__version__ = ENGINE_VERSION

_EXPORT_MODULES = {
    "AC_REQUEST_CONTRACT": "analyses",
    "AC_RESULT_CONTRACT": "analyses",
    "FOURIER_RESULT_CONTRACT": "analyses",
    "TRANSFER_RESULT_CONTRACT": "analyses",
    "AcExcitation": "analyses",
    "AcSweep": "analyses",
    "reduce_fourier_result": "analyses",
    "run_ac_analysis": "analyses",
    "run_transfer_function": "analyses",
    "NOISE_RESULT_CONTRACT": "advanced_analyses",
    "POLE_ZERO_RESULT_CONTRACT": "advanced_analyses",
    "SENSITIVITY_RESULT_CONTRACT": "advanced_analyses",
    "run_ac_sensitivity": "advanced_analyses",
    "run_linear_noise_analysis": "advanced_analyses",
    "run_linear_pole_zero": "advanced_analyses",
    "BEHAVIORAL_EXPRESSION_CONTRACT": "behavioral",
    "BehavioralEvaluation": "behavioral",
    "BehavioralSignal": "behavioral",
    "CompiledBehavioralExpression": "behavioral",
    "compile_behavioral_expression": "behavioral",
    "ADJOINT_SENSITIVITY_CONTRACT": "nonlinear_analyses",
    "BIASED_NOISE_CONTRACT": "nonlinear_analyses",
    "FREQUENCY_VOLTERRA_CONTRACT": "nonlinear_analyses",
    "MULTITONE_VOLTERRA_CONTRACT": "nonlinear_analyses",
    "LOCAL_DISTORTION_CONTRACT": "nonlinear_analyses",
    "NONLINEAR_OP_CONTRACT": "nonlinear_analyses",
    "NONLINEAR_SMALL_SIGNAL_CONTRACT": "nonlinear_analyses",
    "NoiseCorrelation": "nonlinear_analyses",
    "VolterraTone": "nonlinear_analyses",
    "TWO_TONE_DISTORTION_CONTRACT": "nonlinear_analyses",
    "run_biased_noise": "nonlinear_analyses",
    "run_frequency_dependent_volterra": "nonlinear_analyses",
    "run_multitone_volterra": "nonlinear_analyses",
    "run_local_distortion": "nonlinear_analyses",
    "run_nonlinear_adjoint_sensitivity": "nonlinear_analyses",
    "run_nonlinear_operating_point": "nonlinear_analyses",
    "run_nonlinear_small_signal": "nonlinear_analyses",
    "run_two_tone_intermodulation": "nonlinear_analyses",
    "NONLINEAR_DECK_REQUEST_CONTRACT": "nonlinear_deck",
    "NONLINEAR_DECK_RESULT_CONTRACT": "nonlinear_deck",
    "NonlinearDeckRequest": "nonlinear_deck",
    "ParsedNonlinearDeck": "nonlinear_deck",
    "parse_nonlinear_analysis_deck": "nonlinear_deck",
    "run_nonlinear_analysis_deck": "nonlinear_deck",
    "AnalysisDirective": "contracts",
    "CircuitElement": "contracts",
    "CircuitProject": "contracts",
    "CircuitResult": "contracts",
    "DiodeModel": "contracts",
    "HierarchyInstance": "contracts",
    "MeasureDirective": "contracts",
    "ProbeDescriptor": "contracts",
    "SourceWaveform": "contracts",
    "StepDirective": "contracts",
    "StepVariant": "contracts",
    "SwitchModel": "contracts",
    "HIL_EVIDENCE_CONTRACT": "hil_certification",
    "HIL_GATE_CONTRACT": "hil_certification",
    "HilRequirements": "hil_certification",
    "evaluate_physical_hil_evidence": "hil_certification",
    "NetlistParseError": "netlist",
    "parse_netlist": "netlist",
    "parse_spice_number": "netlist",
    "BUILTIN_LIBRARY": "library",
    "ArchetypeLibrary": "library",
    "ArchetypeLibraryError": "library",
    "ArchetypeUnavailableError": "library",
    "ArchetypeDescriptor": "library_contracts",
    "ArchetypePreset": "library_contracts",
    "ParameterSpec": "library_contracts",
    "DigitalConvergenceError": "digital",
    "DigitalKernel": "digital",
    "DigitalModelError": "digital",
    "DigitalTransition": "digital",
    "LogicValue": "digital",
    "resolve_logic": "digital",
    "BehavioralFlags": "device_contracts",
    "DeviceDescriptor": "device_contracts",
    "DeviceExtensionManifest": "device_contracts",
    "DeviceValidityEnvelope": "device_contracts",
    "DeviceVariable": "device_contracts",
    "ElectricalTerminal": "device_contracts",
    "PowerPort": "device_contracts",
    "RuntimeProvenance": "device_contracts",
    "SolverInterface": "device_contracts",
    "ValidityBound": "device_contracts",
    "DeviceExtensionError": "device_extensions",
    "DeviceExtensionRegistry": "device_extensions",
    "IVEvaluation": "device_extensions",
    "PolynomialIVDevice": "device_extensions",
    "RegistryLimits": "device_extensions",
    "TableIVDevice": "device_extensions",
    "DYNAMIC_DIODE_CONTRACT": "dynamic_devices",
    "DynamicDeviceModelError": "dynamic_devices",
    "DynamicDiodeEvaluation": "dynamic_devices",
    "DynamicDiodeModel": "dynamic_devices",
    "DynamicDiodeTransientEvaluation": "dynamic_devices",
    "DynamicDiodeValidity": "dynamic_devices",
    "ReverseRecoveryState": "dynamic_devices",
    "STATIC_COMPACT_CONTRACT": "static_compact_devices",
    "EbersMollBJT": "static_compact_devices",
    "Level1MOSFET": "static_compact_devices",
    "ShichmanHodgesJFET": "static_compact_devices",
    "StaticDeviceValidity": "static_compact_devices",
    "TerminalDCEvaluation": "static_compact_devices",
    "compile_project": "runner",
    "native_request": "runner",
    "run_project": "runner",
    "CORNER_SWEEP_CONTRACT": "sweeps",
    "MONTE_CARLO_CONTRACT": "sweeps",
    "TEMPERATURE_SWEEP_CONTRACT": "sweeps",
    "RelativeVariation": "sweeps",
    "TemperatureCoefficient": "sweeps",
    "run_corner_sweep": "sweeps",
    "run_monte_carlo": "sweeps",
    "run_temperature_sweep": "sweeps",
    "run_native_project": "native_runner",
    "NativeABIError": "native_abi",
    "NativeCircuit": "native_abi",
    "NativeLibrary": "native_abi",
    "NativeResult": "native_abi",
    "NativeTransientCheckpoint": "native_abi",
    "NativeTransientResult": "native_abi",
    "NativeTransientSession": "native_abi",
    "load_native_library": "native_abi",
    "LibraryExportError": "model_builder",
    "ModelBuilder": "model_builder",
    "ModelBuilderError": "model_builder",
    "QualificationError": "model_builder",
    "QualificationPolicy": "model_builder",
    "ShockleyDiodeFitter": "model_builder",
    "export_archetype": "model_builder",
    "llm_draft_source": "model_builder",
    "qualify_model": "model_builder",
    "BlackBoxDescriptor": "model_builder_contracts",
    "CurveDataset": "model_builder_contracts",
    "DatasetColumn": "model_builder_contracts",
    "DomainBound": "model_builder_contracts",
    "ModelPackage": "model_builder_contracts",
    "ParameterDefinition": "model_builder_contracts",
    "SourceArtifact": "model_builder_contracts",
    "ValidityEnvelope": "model_builder_contracts",
    "KiCadModelMapping": "model_library",
    "QualifiedModelLibrary": "model_library",
    "QualifiedModelRecord": "model_library",
    "RedistributionApproval": "model_library",
    "COMPILED_BLOCK_APPROVAL_CONTRACT": "compiled_blocks",
    "COMPILED_BLOCK_MANIFEST_CONTRACT": "compiled_blocks",
    "COMPILED_BLOCK_REQUEST_CONTRACT": "compiled_blocks",
    "COMPILED_BLOCK_RESPONSE_CONTRACT": "compiled_blocks",
    "CompiledBlockApproval": "compiled_blocks",
    "CompiledBlockError": "compiled_blocks",
    "CompiledBlockExecutionError": "compiled_blocks",
    "CompiledBlockManifest": "compiled_blocks",
    "CompiledBlockProcessRuntime": "compiled_blocks",
    "CompiledBlockRequest": "compiled_blocks",
    "CompiledBlockResponse": "compiled_blocks",
    "CompiledBlockRuntimeLimits": "compiled_blocks",
    "CompilerTool": "hdl_frontend",
    "HdlCompileError": "hdl_frontend",
    "HdlCompilePlan": "hdl_frontend",
    "HdlFrontendError": "hdl_frontend",
    "OsdiModuleManifest": "hdl_frontend",
    "compiled_isolation_profile": "hdl_frontend",
    "compile_hdl": "hdl_frontend",
    "discover_hdl_toolchains": "hdl_frontend",
    "EngineAdapterManifest": "public_benchmark",
    "EngineCaseEvidence": "public_benchmark",
    "JsonProcessBenchmarkAdapter": "public_benchmark",
    "MetricTolerance": "public_benchmark",
    "PublicBenchmarkCase": "public_benchmark",
    "PublicBenchmarkError": "public_benchmark",
    "PublicBenchmarkExecutionError": "public_benchmark",
    "PublicBenchmarkManifest": "public_benchmark",
    "PublicSource": "public_benchmark",
    "qualify_public_benchmark": "public_benchmark",
    "PUBLIC_LADDER_SIZES": "public_corpus",
    "PublicCorpusError": "public_corpus",
    "render_ladder_deck": "public_corpus",
    "run_local_equal_model_evidence": "public_corpus",
    "validate_staged_corpus": "public_corpus",
    "NativeOsdiCallbackRuntime": "osdi_runtime",
    "NgspiceOsdiSandboxRuntime": "osdi_runtime",
    "OSDI_NATIVE_CALLBACK_CONTRACT": "osdi_runtime",
    "OsdiExecutionError": "osdi_runtime",
    "OsdiSandboxPolicy": "osdi_runtime",
    "CompiledBlock": "session_contracts",
    "ControlType": "session_contracts",
    "InputDescriptor": "session_contracts",
    "SessionCheckpoint": "session_contracts",
    "SessionEvent": "session_contracts",
    "SessionStats": "session_contracts",
    "SignalDescriptor": "session_contracts",
    "FunctionalPlant": "session",
    "Lifecycle": "session",
    "SimulationSession": "session",
    "VirtualClockScheduler": "session",
    "WallClockScheduler": "session",
    "AcquisitionStatus": "instrument_contracts",
    "CalibrationRecord": "instrument_contracts",
    "CalibrationState": "instrument_contracts",
    "FrequencyResponse": "instrument_contracts",
    "Measurement": "instrument_contracts",
    "SampledWaveform": "instrument_contracts",
    "ScopeCapture": "instrument_contracts",
    "SmithPoint": "instrument_contracts",
    "SpectrumTrace": "instrument_contracts",
    "DMM": "instruments",
    "InstrumentError": "instruments",
    "NetworkAnalyzer": "instruments",
    "Scope": "instruments",
    "ScopeTrigger": "instruments",
    "SpectrumAnalyzer": "instruments",
    "impedance_to_reflection": "instruments",
    "reflection_to_impedance": "instruments",
    "smith_coordinates": "instruments",
    "SessionCaptureMonitor": "instrument_session",
    "SessionWaveformRecorder": "instrument_session",
    "native_transient_waveform": "instrument_session",
    "CapturedEvent": "streaming_contracts",
    "SampleWindow": "streaming_contracts",
    "StreamChannel": "streaming_contracts",
    "TriggerSpec": "streaming_contracts",
    "UniformStreamSchema": "streaming_contracts",
    "EventCaptureEngine": "streaming",
    "RollingSampleBuffer": "streaming",
    "StreamCaptureError": "streaming",
    "ChunkedWaveformReader": "waveform_store",
    "ChunkedWaveformWriter": "waveform_store",
    "WaveformChunk": "waveform_store",
    "WaveformSizeLimitError": "waveform_store",
    "WaveformStoreError": "waveform_store",
    "compare_codecs": "waveform_store",
    "QUALIFICATION_CASE_CONTRACT": "qualification",
    "QUALIFICATION_REPORT_CONTRACT": "qualification",
    "run_qualification_suite": "qualification",
    "ENGINE_VERSION": "version"
}


def __getattr__(name):
    module = _EXPORT_MODULES.get(name)
    if module is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(_import_module("." + module, __name__), name)
    globals()[name] = value
    return value


def __dir__():
    return sorted(set(globals()) | set(__all__))


__all__ = [
    "AC_REQUEST_CONTRACT",
    "AC_RESULT_CONTRACT",
    "FOURIER_RESULT_CONTRACT",
    "TRANSFER_RESULT_CONTRACT",
    "AcExcitation",
    "AcSweep",
    "ADJOINT_SENSITIVITY_CONTRACT",
    "BEHAVIORAL_EXPRESSION_CONTRACT",
    "BIASED_NOISE_CONTRACT",
    "BehavioralEvaluation",
    "BehavioralSignal",
    "CompiledBehavioralExpression",
    "LOCAL_DISTORTION_CONTRACT",
    "NONLINEAR_OP_CONTRACT",
    "NONLINEAR_SMALL_SIGNAL_CONTRACT",
    "NOISE_RESULT_CONTRACT",
    "POLE_ZERO_RESULT_CONTRACT",
    "SENSITIVITY_RESULT_CONTRACT",
    "AnalysisDirective",
    "AcquisitionStatus",
    "CircuitElement",
    "DiodeModel",
    "CircuitProject",
    "CircuitResult",
    "CalibrationRecord",
    "CalibrationState",
    "CORNER_SWEEP_CONTRACT",
    "CompiledBlock",
    "COMPILED_BLOCK_APPROVAL_CONTRACT",
    "COMPILED_BLOCK_MANIFEST_CONTRACT",
    "COMPILED_BLOCK_REQUEST_CONTRACT",
    "COMPILED_BLOCK_RESPONSE_CONTRACT",
    "CompiledBlockApproval",
    "CompiledBlockError",
    "CompiledBlockExecutionError",
    "CompiledBlockManifest",
    "CompiledBlockProcessRuntime",
    "CompiledBlockRequest",
    "CompiledBlockResponse",
    "CompiledBlockRuntimeLimits",
    "CompilerTool",
    "HdlCompileError",
    "HdlCompilePlan",
    "HdlFrontendError",
    "OsdiModuleManifest",
    "compiled_isolation_profile",
    "compile_hdl",
    "discover_hdl_toolchains",
    "EngineAdapterManifest",
    "EngineCaseEvidence",
    "JsonProcessBenchmarkAdapter",
    "MetricTolerance",
    "PublicBenchmarkCase",
    "PublicBenchmarkError",
    "PublicBenchmarkExecutionError",
    "PublicBenchmarkManifest",
    "PublicSource",
    "qualify_public_benchmark",
    "PUBLIC_LADDER_SIZES",
    "PublicCorpusError",
    "render_ladder_deck",
    "run_local_equal_model_evidence",
    "validate_staged_corpus",
    "NgspiceOsdiSandboxRuntime",
    "OsdiExecutionError",
    "OsdiSandboxPolicy",
    "ControlType",
    "FunctionalPlant",
    "FrequencyResponse",
    "InputDescriptor",
    "InstrumentError",
    "Lifecycle",
    "HierarchyInstance",
    "MeasureDirective",
    "ArchetypeDescriptor",
    "ArchetypeLibrary",
    "ArchetypeLibraryError",
    "ArchetypePreset",
    "ArchetypeUnavailableError",
    "BUILTIN_LIBRARY",
    "DigitalConvergenceError",
    "DigitalKernel",
    "DigitalModelError",
    "DigitalTransition",
    "BehavioralFlags",
    "DeviceDescriptor",
    "DeviceExtensionError",
    "DeviceExtensionManifest",
    "DeviceExtensionRegistry",
    "DeviceValidityEnvelope",
    "DeviceVariable",
    "DYNAMIC_DIODE_CONTRACT",
    "DynamicDeviceModelError",
    "DynamicDiodeEvaluation",
    "DynamicDiodeModel",
    "DynamicDiodeTransientEvaluation",
    "DynamicDiodeValidity",
    "EbersMollBJT",
    "ElectricalTerminal",
    "IVEvaluation",
    "LogicValue",
    "Level1MOSFET",
    "Measurement",
    "MONTE_CARLO_CONTRACT",
    "NetlistParseError",
    "NativeABIError",
    "NativeCircuit",
    "NativeLibrary",
    "NativeResult",
    "NativeTransientCheckpoint",
    "NativeTransientResult",
    "NativeTransientSession",
    "ProbeDescriptor",
    "SourceWaveform",
    "RelativeVariation",
    "StepDirective",
    "StepVariant",
    "HIL_EVIDENCE_CONTRACT",
    "HIL_GATE_CONTRACT",
    "HilRequirements",
    "evaluate_physical_hil_evidence",
    "SwitchModel",
    "DMM",
    "NetworkAnalyzer",
    "SampledWaveform",
    "Scope",
    "ScopeCapture",
    "ScopeTrigger",
    "PowerPort",
    "PolynomialIVDevice",
    "RegistryLimits",
    "RuntimeProvenance",
    "ReverseRecoveryState",
    "STATIC_COMPACT_CONTRACT",
    "SessionCheckpoint",
    "SessionCaptureMonitor",
    "SessionEvent",
    "SessionStats",
    "SessionWaveformRecorder",
    "CapturedEvent",
    "ChunkedWaveformReader",
    "ChunkedWaveformWriter",
    "EventCaptureEngine",
    "RollingSampleBuffer",
    "SampleWindow",
    "StreamCaptureError",
    "StreamChannel",
    "TriggerSpec",
    "UniformStreamSchema",
    "WaveformChunk",
    "WaveformSizeLimitError",
    "WaveformStoreError",
    "SignalDescriptor",
    "SmithPoint",
    "SpectrumAnalyzer",
    "SpectrumTrace",
    "SimulationSession",
    "VirtualClockScheduler",
    "WallClockScheduler",
    "ParameterSpec",
    "BlackBoxDescriptor",
    "CurveDataset",
    "DatasetColumn",
    "DomainBound",
    "LibraryExportError",
    "KiCadModelMapping",
    "ModelBuilder",
    "ModelBuilderError",
    "ModelPackage",
    "ParameterDefinition",
    "QualificationError",
    "QualificationPolicy",
    "QualifiedModelLibrary",
    "QualifiedModelRecord",
    "QUALIFICATION_CASE_CONTRACT",
    "QUALIFICATION_REPORT_CONTRACT",
    "ShockleyDiodeFitter",
    "RedistributionApproval",
    "SolverInterface",
    "SourceArtifact",
    "ValidityEnvelope",
    "ValidityBound",
    "TableIVDevice",
    "ShichmanHodgesJFET",
    "StaticDeviceValidity",
    "TerminalDCEvaluation",
    "TEMPERATURE_SWEEP_CONTRACT",
    "TemperatureCoefficient",
    "compile_project",
    "compare_codecs",
    "export_archetype",
    "impedance_to_reflection",
    "llm_draft_source",
    "load_native_library",
    "native_request",
    "native_transient_waveform",
    "parse_netlist",
    "parse_spice_number",
    "run_project",
    "run_corner_sweep",
    "run_monte_carlo",
    "run_temperature_sweep",
    "run_ac_analysis",
    "run_ac_sensitivity",
    "compile_behavioral_expression",
    "run_biased_noise",
    "NoiseCorrelation",
    "FREQUENCY_VOLTERRA_CONTRACT",
    "MULTITONE_VOLTERRA_CONTRACT",
    "run_frequency_dependent_volterra",
    "VolterraTone",
    "run_multitone_volterra",
    "run_local_distortion",
    "run_nonlinear_adjoint_sensitivity",
    "run_nonlinear_operating_point",
    "run_nonlinear_small_signal",
    "TWO_TONE_DISTORTION_CONTRACT",
    "run_two_tone_intermodulation",
    "NONLINEAR_DECK_REQUEST_CONTRACT",
    "NONLINEAR_DECK_RESULT_CONTRACT",
    "NonlinearDeckRequest",
    "ParsedNonlinearDeck",
    "parse_nonlinear_analysis_deck",
    "run_nonlinear_analysis_deck",
    "run_linear_noise_analysis",
    "run_linear_pole_zero",
    "run_native_project",
    "run_qualification_suite",
    "run_transfer_function",
    "reduce_fourier_result",
    "qualify_model",
    "reflection_to_impedance",
    "resolve_logic",
    "smith_coordinates",
]
