# SPDX-License-Identifier: Apache-2.0
"""Complete mesh handoff and result ingestion through the public extension API."""

import unittest
from copy import deepcopy
from pathlib import Path

from python.spike_core.extensions import ExtensionManifest, ExtensionRegistry
from python.spike_core.extension_analysis_results import admit_analysis_result, design_binding
from python.spike_core.extension_mesh_exchange import build_extension_mesh_exchange


EXAMPLES = Path(__file__).resolve().parents[2] / "extension_sdk" / "examples"
DESIGN = {
    "contract": "spike/v1", "design_id": "mesh-board", "name": "Mesh board",
    "source_format": "test", "units": "mm",
    "layers": [{"name": "F.Cu"}], "nets": [{"id": "1", "name": "VCC"}],
    "tracks": [{"id": "T1", "net_name": "VCC", "layer": "F.Cu",
                "start": [0, 0], "end": [4, 0], "width": 0.4}],
    "vias": [], "pads": [], "zones": [], "components": [],
    "stackup": [{"name": "F.Cu", "type": "copper", "thickness": 0.035}],
    "issues": [], "metadata": {},
}


class ExtensionMeshExchangeTest(unittest.TestCase):
    def test_complete_topology_is_distinct_from_sampled_preview(self):
        design = deepcopy(DESIGN)
        design["tracks"][0]["end"] = [10, 0]
        exchange = build_extension_mesh_exchange(design, {"mode": "dc", "net_names": ["VCC"],
            "mesh": {"target_size_mm": 0.05, "max_conductors": 2048,
                     "max_preview_cells": 100}}, design_binding(design))
        self.assertFalse(exchange["mesh"]["truncated"])
        self.assertGreater(exchange["mesh"]["cell_count"], exchange["mesh_preview"]["cell_count"])
        self.assertTrue(exchange["mesh_preview"]["truncated"])
        self.assertEqual(exchange["solver_geometry"]["contract"], "spike/solver-geometry/v1")
        self.assertEqual(exchange["mesh_binding"]["design_digest_sha256"], design_binding(design)["digest_sha256"])

    def test_process_exchange_passes_mesh_and_ingests_visuals(self):
        registry = ExtensionRegistry()
        registry.discover([EXAMPLES])
        registry.trust("org.example.mesh-field-adapter")
        result = registry.invoke("org.example.mesh-field-adapter", "import-mesh-voltage-field", {
            "design": DESIGN,
            "parameters": {"samples": [{"x_mm": 2, "y_mm": 0, "layer": "F.Cu", "value": 3.3}],
                           "mesh_spec": {"mode": "dc", "net_names": ["VCC"],
                                         "mesh": {"target_size_mm": 0.5,
                                                  "max_conductors": 256,
                                                  "max_preview_cells": 100}}},
        })
        admitted = result["data"]["analysis_result"]
        self.assertEqual(admitted["model_status"], "unvalidated")
        self.assertEqual(admitted["fields"]["visualization"]["scalar_fields"]["voltage_v"][0]["value"], 3.3)
        self.assertGreater(admitted["summary"]["input_mesh_branches"], 0)
        self.assertTrue(admitted["fields"]["visualization"]["mesh"])
        self.assertEqual(len(admitted["provenance"]["input_mesh_sha256"]), 64)
        self.assertEqual(len(admitted["provenance"]["input_analysis_spec_sha256"]), 64)
        self.assertEqual(admitted["provenance"]["extension_id"], "org.example.mesh-field-adapter")

    def test_mesh_permission_and_host_ownership_are_enforced(self):
        with self.assertRaisesRegex(ValueError, "requires design.read"):
            ExtensionManifest.from_dict({
                "id": "bad.mesh", "name": "Bad", "version": "1", "provider": "Tests",
                "description": "Bad", "runtime": "python", "entrypoint": "run.py",
                "permissions": ["mesh.read", "results.write"],
                "contributes": {"analyses": [{"id": "solve", "name": "Solve",
                                            "output_contract": "spike/v1"}]},
            })
        registry = ExtensionRegistry()
        registry.discover([EXAMPLES])
        registry.trust("org.example.mesh-field-adapter")
        with self.assertRaisesRegex(ValueError, "generated by the SPIKE host"):
            registry.invoke("org.example.mesh-field-adapter", "import-mesh-voltage-field",
                            {"design": DESIGN, "mesh": {"cells": []}})
        with self.assertRaisesRegex(ValueError, "max_conductors"):
            registry.invoke("org.example.mesh-field-adapter", "import-mesh-voltage-field",
                            {"design": DESIGN, "parameters": {"mesh_spec": {
                                "mesh": {"max_conductors": 8193}}}})

    def test_returned_result_must_cite_exact_host_mesh(self):
        binding = design_binding(DESIGN)
        result = {"contract": "spike/v1", "analysis_id": "mesh-result", "status": "completed",
            "mode": "dc", "model_status": "unvalidated", "summary": {}, "fields": {},
            "networks": {}, "probes": [], "issues": [], "provenance": {
                "design_id": binding["design_id"], "design_digest_sha256": binding["digest_sha256"],
                "solver": "test", "input_mesh_sha256": "0" * 64}}
        with self.assertRaisesRegex(ValueError, "mesh binding"):
            admit_analysis_result(result, binding, extension_id="fixture.mesh",
                                  expected_mesh_digest="1" * 64)
        with self.assertRaisesRegex(ValueError, "analysis specification"):
            admit_analysis_result(result, binding, extension_id="fixture.mesh",
                                  expected_mesh_digest="0" * 64,
                                  expected_spec_digest="1" * 64)


if __name__ == "__main__":
    unittest.main()
