"""
SPIKE Reports Panel — Phase 15
Live HTML report rendered from actual simulation data with dynamic WebGL.
Supports: Interactive 3D/2D views, comprehensive auditing.
Export to PDF via native browser print.
"""
import wx
import wx.html
import datetime
import os
import base64
import tempfile

try:
    import wx.html2
    HAS_WV = True
except ImportError:
    HAS_WV = False

# ---------------------------------------------------------------------------
# HTML template helpers
# ---------------------------------------------------------------------------

_CSS = """
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; font-family: 'Segoe UI', Arial, sans-serif; }
  body { background: #f0f2f5; color: #333; padding: 40px; line-height: 1.6; }
  .report-container { max-width: 1000px; margin: 0 auto; background: #fff; padding: 40px; box-shadow: 0 4px 15px rgba(0,0,0,0.05); border-radius: 8px; }
  h1, h2, h3 { color: #1a2a3a; margin-bottom: 15px; }
  .header { border-bottom: 3px solid #e94560; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: flex-end; }
  .header h1 { font-size: 32px; letter-spacing: 1px; color: #0f3460; margin: 0; }
  .meta-info { text-align: right; font-size: 13px; color: #666; }
  .section { margin-bottom: 30px; }
  .section h2 { font-size: 20px; border-bottom: 1px solid #eee; padding-bottom: 8px; color: #0f3460; }
  .metrics { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin-top: 15px; }
  .metric { background: #f8f9fa; border-left: 4px solid #e94560; padding: 15px; border-radius: 4px; }
  .m-label { font-size: 12px; color: #666; text-transform: uppercase; font-weight: 600; }
  .m-value { font-size: 24px; font-weight: bold; color: #1a2a3a; margin-top: 5px; }
  table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 14px; }
  th, td { padding: 12px 15px; text-align: left; border-bottom: 1px solid #ddd; }
  th { background: #0f3460; color: #fff; font-weight: 600; }
  tr:nth-child(even) { background: #f8f9fa; }
  .pass { color: #28a745; font-weight: bold; }
  .warn { color: #ffc107; font-weight: bold; }
  .fail { color: #dc3545; font-weight: bold; }
  .interactive-container { width: 100%; height: 500px; border: 1px solid #ccc; border-radius: 4px; overflow: hidden; margin-top: 15px; }
  iframe { width: 100%; height: 100%; border: none; }
  .img-container { text-align: center; margin: 15px 0; }
  .img-container img { max-width: 100%; border: 1px solid #eee; border-radius: 4px; }
  @media print {
      body { padding: 0; background: #fff; }
      .report-container { box-shadow: none; padding: 0; max-width: 100%; }
      .interactive-container { display: none; } /* Hide interactive 3D in print, replace with static if needed */
  }
</style>
"""

def _now():
    return datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def build_html_report(metrics: dict, probes: list, params: dict, config: dict, viewport_html: str = "", charts: dict = None) -> str:
    board = params.get("board", "Unknown Board")
    mode  = params.get("mode", "DC IR-Drop")
    project = params.get("project", "SPIKE Project")
    user = params.get("user", os.getlogin())
    ts    = _now()
    
    html_parts = [f"<!DOCTYPE html><html><head><meta charset='UTF-8'>{_CSS}</head><body><div class='report-container'>"]
    
    # Header
    html_parts.append(f"""
    <div class='header'>
        <div>
            <h1>⚡ SPIKE Analysis Report</h1>
            <h3 style='color:#666; margin-top:5px;'>{project} - {board}</h3>
        </div>
        <div class='meta-info'>
            <div><strong>Analysis:</strong> {mode}</div>
            <div><strong>Generated By:</strong> {user}</div>
            <div><strong>Date:</strong> {ts}</div>
        </div>
    </div>
    """)
    
    if config.get("exec_summary", True):
        drop  = metrics.get("drop_mv", 0)
        minv  = metrics.get("min_v", 0)
        maxj  = metrics.get("max_j", 0)
        eff   = metrics.get("efficiency", 0)
        
        drop_cls = "fail" if drop > 100 else ("warn" if drop > 50 else "pass")
        j_cls    = "fail" if maxj > 200 else ("warn" if maxj > 100 else "pass")
        
        html_parts.append(f"""
        <div class="section">
            <h2>📊 Executive Summary</h2>
            <div class="metrics">
              <div class="metric"><div class="m-label">Max IR Drop</div><div class="m-value"><span class="{drop_cls}">{drop:.1f} mV</span></div></div>
              <div class="metric"><div class="m-label">Min Voltage</div><div class="m-value">{minv:.3f} V</div></div>
              <div class="metric"><div class="m-label">Max J</div><div class="m-value"><span class="{j_cls}">{maxj:.1f} A/mm²</span></div></div>
              <div class="metric"><div class="m-label">Efficiency</div><div class="m-value">{eff:.1f}%</div></div>
            </div>
        </div>
        """)
        
        # Sinks
        sinks = metrics.get("sinks", [])
        if sinks:
            sink_rows = ""
            for i, s in enumerate(sinks):
                dc = "pass" if s.get("drop", 999) < 100 else "warn"
                sink_rows += f"<tr><td>Sink #{i+1}</td><td>{s.get('v', 0):.4f} V</td><td><span class='{dc}'>{s.get('drop', 0):.1f} mV</span></td><td>{'✓ OK' if dc=='pass' else '⚠ Review'}</td></tr>"
            
            html_parts.append(f"""
            <div class="section">
              <h2>📉 Sink Performance</h2>
              <table><tr><th>Sink ID</th><th>Voltage</th><th>IR Drop</th><th>Status</th></tr>{sink_rows}</table>
            </div>
            """)

    if config.get("sim_settings", True):
        param_rows = "".join(f"<tr><td><strong>{k}</strong></td><td>{v}</td></tr>" for k, v in params.items())
        html_parts.append(f"""
        <div class="section">
            <h2>🔧 Simulation Settings & Auditing</h2>
            <table>{param_rows}</table>
        </div>
        """)

    if config.get("interactive_3d", True) and viewport_html:
        html_parts.append(f"""
        <div class="section">
            <h2>🎛️ Interactive 3D WebGL Viewport</h2>
            <p style='font-size:12px;color:#666;'><i>Note: Interactive 3D viewer is disabled when printing to PDF.</i></p>
            <div class="interactive-container">
                <iframe srcdoc="{viewport_html.replace('"', '&quot;')}"></iframe>
            </div>
        </div>
        """)
        
    if config.get("charts", True) and charts:
        html_parts.append("<div class='section'><h2>📈 2D Analysis Charts</h2>")
        for title, b64_img in charts.items():
            html_parts.append(f"<h3>{title}</h3><div class='img-container'><img src='data:image/png;base64,{b64_img}'/></div>")
        html_parts.append("</div>")

    if config.get("probes", True) and probes:
        probe_rows = ""
        for p in probes:
            v_str = f"{p['v']:.5f}" if p.get('v') is not None else "—"
            j_str = f"{p['j']:.3f}" if p.get('j') is not None else "—"
            z_str = f"{p['z']:.4f}" if p.get('z') is not None else "—"
            probe_rows += f"<tr><td>{p['id']}</td><td>{p['net']}</td><td>{p['layer']}</td><td>{v_str}</td><td>{j_str}</td><td>{z_str}</td><td>{p.get('notes','')}</td></tr>"
        html_parts.append(f"""
        <div class="section">
            <h2>🔬 Probe Measurements</h2>
            <table><tr><th>ID</th><th>Net</th><th>Layer</th><th>V (V)</th><th>J (A/mm²)</th><th>Z (mΩ)</th><th>Notes</th></tr>{probe_rows}</table>
        </div>
        """)

    html_parts.append("</div></body></html>")
    return "".join(html_parts)

# ---------------------------------------------------------------------------
# Panel
# ---------------------------------------------------------------------------

class ReportsPanel(wx.Panel):
    """Dynamic HTML report panel with interactive WebGL."""

    def __init__(self, parent):
        super().__init__(parent)
        self._metrics = {}
        self._probes  = []
        self._params  = {"mode": "DC IR-Drop", "board": "—"}
        self._html    = ""
        self._build_ui()

    def _build_ui(self):
        outer = wx.BoxSizer(wx.VERTICAL)

        # Toolbar
        tb = wx.BoxSizer(wx.HORIZONTAL)
        self.btn_gen       = wx.Button(self, label="🔄 Generate Report")
        self.btn_export_html = wx.Button(self, label="🌐 Save HTML")
        self.btn_print       = wx.Button(self, label="📄 Print to PDF")

        tb.Add(self.btn_gen,         0, wx.RIGHT, 6)
        tb.Add(self.btn_export_html, 0, wx.RIGHT, 6)
        tb.Add(self.btn_print,       0, wx.RIGHT, 20)

        tb.AddStretchSpacer()
        outer.Add(tb, 0, wx.EXPAND | wx.ALL, 8)
        
        # Configuration checkboxes
        cfg_box = wx.StaticBox(self, label="Report Builder Checklist")
        cfg_sizer = wx.StaticBoxSizer(cfg_box, wx.HORIZONTAL)
        
        self.chk_exec = wx.CheckBox(cfg_box, label="Executive Summary")
        self.chk_settings = wx.CheckBox(cfg_box, label="Simulation Settings")
        self.chk_3d = wx.CheckBox(cfg_box, label="Interactive 3D WebGL")
        self.chk_charts = wx.CheckBox(cfg_box, label="2D Analysis Charts")
        self.chk_probes = wx.CheckBox(cfg_box, label="Probe Data")
        
        self.chk_exec.SetValue(True)
        self.chk_settings.SetValue(True)
        self.chk_3d.SetValue(True)
        self.chk_charts.SetValue(True)
        self.chk_probes.SetValue(True)
        
        cfg_sizer.Add(self.chk_exec, 0, wx.RIGHT, 10)
        cfg_sizer.Add(self.chk_settings, 0, wx.RIGHT, 10)
        cfg_sizer.Add(self.chk_3d, 0, wx.RIGHT, 10)
        cfg_sizer.Add(self.chk_charts, 0, wx.RIGHT, 10)
        cfg_sizer.Add(self.chk_probes, 0, wx.RIGHT, 10)
        
        outer.Add(cfg_sizer, 0, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.BOTTOM, 8)

        # Report viewer
        global HAS_WV
        if HAS_WV:
            try:
                self.viewer = wx.html2.WebView.New(self)
                self.viewer.SetPage("<body style='background:#f0f2f5;color:#333;font-family:sans-serif;'><div style='padding:40px;text-align:center;'><h2>Ready to Generate Report</h2><p>Load a board, run a simulation, then click Generate Report.</p></div></body>", "")
            except Exception:
                HAS_WV = False
                self.viewer = wx.html.HtmlWindow(self)
        else:
            self.viewer = wx.html.HtmlWindow(self)
            self.viewer.SetPage("<body>Load a board and run a simulation.</body>")

        outer.Add(self.viewer, 1, wx.EXPAND | wx.ALL, 6)
        self.SetSizer(outer)

        # Bindings
        self.btn_gen.Bind(wx.EVT_BUTTON,         self._on_generate)
        self.btn_export_html.Bind(wx.EVT_BUTTON, self._on_export_html)
        self.btn_print.Bind(wx.EVT_BUTTON,       self._on_print)

    def update_from_simulation(self, metrics: dict, probes: list, params: dict):
        self._metrics = metrics
        self._probes  = probes
        self._params  = params
        self._on_generate(None)

    def _on_generate(self, event):
        config = {
            "exec_summary": self.chk_exec.GetValue(),
            "sim_settings": self.chk_settings.GetValue(),
            "interactive_3d": self.chk_3d.GetValue(),
            "charts": self.chk_charts.GetValue(),
            "probes": self.chk_probes.GetValue()
        }
        
        viewport_html = ""
        charts_b64 = {}
        
        # Try to extract PyVista 3D HTML and Matplotlib Charts from parent context
        try:
            tlp = self.GetTopLevelParent()
            if hasattr(tlp, "viewport") and tlp.viewport.plotter:
                # Export PyVista to HTML string
                temp_html = os.path.join(tempfile.gettempdir(), "spike_3d_export.html")
                tlp.viewport.plotter.export_html(temp_html)
                with open(temp_html, 'r', encoding='utf-8') as f:
                    viewport_html = f.read()
                os.remove(temp_html)
            
            if hasattr(tlp, "analysis_panel") and hasattr(tlp.analysis_panel, "figure"):
                import io
                buf = io.BytesIO()
                tlp.analysis_panel.figure.savefig(buf, format='png', bbox_inches='tight')
                buf.seek(0)
                charts_b64["Analysis Plot"] = base64.b64encode(buf.read()).decode('utf-8')
        except Exception as e:
            print(f"Warning: Could not capture visual exports: {e}")

        self._html = build_html_report(self._metrics, self._probes, self._params, config, viewport_html, charts_b64)
        
        if isinstance(self.viewer, wx.html.HtmlWindow):
            self.viewer.SetPage(self._html)
        else:
            self.viewer.SetPage(self._html, "")

    def _on_export_html(self, event):
        if not self._html:
            self._on_generate(None)
        dlg = wx.FileDialog(self, "Export HTML Report", wildcard="HTML (*.html)|*.html",
                            style=wx.FD_SAVE | wx.FD_OVERWRITE_PROMPT)
        if dlg.ShowModal() == wx.ID_OK:
            with open(dlg.GetPath(), "w", encoding="utf-8") as f:
                f.write(self._html)
            wx.MessageBox("Interactive HTML Report exported successfully.", "Done", wx.OK | wx.ICON_INFORMATION)
        dlg.Destroy()

    def _on_print(self, event):
        if isinstance(self.viewer, wx.html.HtmlWindow):
            self.viewer.PrintPage(self._html)
        else:
            try:
                self.viewer.Print()
            except Exception as e:
                wx.MessageBox(f"Print failed: {e}", "Error", wx.ICON_ERROR)
