# SPDX-License-Identifier: MIT
# Copyright (c) 2026 SigHarmonic
"""Trusted source payload for the isolated openEMS adapter process."""
import math

# One trusted implementation is used in host admission and the isolated worker.
# This constant is authored code, never user-supplied executable text.
PAD_POLYGON_SOURCE = r'''
def pad_polygon(pad):
    if pad.get("shape", "circle") != "rect" or pad.get("custom_geometry"):
        raise ValueError("GEOMETRY_PAD_CONTOUR_UNQUALIFIED")
    if any(pad.get(key) for key in ("drill", "drill_size_mm", "drill_shape", "plated")):
        raise ValueError("GEOMETRY_PADSTACK_UNMODELED")
    def numeric(value):
        try:
            return not isinstance(value, bool) and isinstance(value, (int, float)) and math.isfinite(value)
        except OverflowError:
            return False
    rotation = pad.get("rotation", pad.get("angle", 0))
    if not numeric(rotation):
        raise ValueError("GEOMETRY_PAD_ROTATION_INVALID")
    center, size = pad.get("at"), pad.get("size")
    if isinstance(center, dict) and set(center) == {"x", "y"}:
        center = [center["x"], center["y"]]
    if (not isinstance(center, (list, tuple)) or len(center) != 2
            or not isinstance(size, (list, tuple)) or len(size) != 2
            or not all(numeric(value) for value in list(center) + list(size))
            or min(size) <= 0):
        raise ValueError("GEOMETRY_PAD_DIMENSIONS_INVALID")
    angle = math.radians(rotation % 360)
    cosine, sine = math.cos(angle), math.sin(angle)
    points = [(center[0] + cosine * dx - sine * dy,
               center[1] + sine * dx + cosine * dy)
              for dx, dy in ((-size[0]/2, -size[1]/2), (size[0]/2, -size[1]/2),
                             (size[0]/2, size[1]/2), (-size[0]/2, size[1]/2))]
    if (not all(numeric(value) for point in points for value in point)
            or any(points[index] == points[(index+1) % 4] for index in range(4))):
        raise ValueError("GEOMETRY_PAD_DIMENSIONS_INVALID")
    return [[point[0] for point in points], [point[1] for point in points]]
'''
exec(compile(PAD_POLYGON_SOURCE, "<spike-pad-geometry>", "exec"))

OPENEMS_DRIVER = r'''#!/usr/bin/env python3
"""Generated by SPIKE. Do not edit if reproducibility is required."""
import argparse, json, math
from pathlib import Path
import numpy as np
from CSXCAD import ContinuousStructure
from openEMS import openEMS
from openEMS.physical_constants import C0, EPS0

def point(value):
    if isinstance(value, dict): return float(value.get("x", 0)), float(value.get("y", 0))
    return float(value[0]), float(value[1])

def net_of(value): return str(value.get("net_name") or value.get("net") or "")

def polygon_coordinates(values):
    points = [point(value) for value in values]
    return [[value[0] for value in points], [value[1] for value in points]]

def pin_mesh_lines(grid, direction, values, tolerance=1e-9):
    lines = np.asarray(grid.GetLines(direction, do_sort=True), dtype=float)
    for value in values:
        if not math.isfinite(float(value)) or lines.size == 0: continue
        index = int(np.argmin(np.abs(lines - float(value))))
        if abs(lines[index] - float(value)) <= tolerance:
            lines[index] = float(value)
    grid.SetLines(direction, np.unique(lines).tolist())

def layer_geometry(stackup):
    z = 0.0
    elevations, ranges = {}, []
    for layer in stackup:
        name = str(layer.get("name", ""))
        kind = str(layer.get("type", "unknown")).lower()
        conductor = kind in {"copper", "conductor"} or name.endswith(".Cu")
        dielectric = kind in {"core", "prepreg", "dielectric", "soldermask", "mask"} or "epsilon_r" in layer or "epsilonR" in layer
        if not conductor and not dielectric: continue
        thickness = max(float(layer.get("thickness", layer.get("thickness_mm", 0.035)) or 0.035), 1e-6)
        if conductor:
            elevations[name] = z
        else:
            ranges.append((layer, z - thickness, z))
            z -= thickness
    return elevations, ranges, z

def polygon_for_track(track):
    a, b = point(track.get("start", [0, 0])), point(track.get("end", [0, 0]))
    width = max(float(track.get("width", 0.1) or 0.1), 1e-6)
    dx, dy = b[0] - a[0], b[1] - a[1]
    length = max(math.hypot(dx, dy), 1e-12)
    nx, ny = -dy / length * width / 2, dx / length * width / 2
    return polygon_coordinates([[a[0] + nx, a[1] + ny], [b[0] + nx, b[1] + ny], [b[0] - nx, b[1] - ny], [a[0] - nx, a[1] - ny]])

__SPIKE_PAD_POLYGON_SOURCE__

def far_field_request(value, f_start, f_stop, sample_limit):
    if value is None: return None
    if not isinstance(value, dict) or value.get("contract") != "spike/openems-far-field-request/v1":
        raise RuntimeError("Authenticated far-field request contract is invalid")
    frequencies = np.asarray(value.get("frequencies_hz", []), dtype=float)
    if frequencies.ndim != 1 or not 1 <= frequencies.size <= 64 or not np.all(np.isfinite(frequencies)) or np.any(frequencies <= 0) or np.any(np.diff(frequencies) <= 0) or np.any(frequencies < f_start) or np.any(frequencies > f_stop):
        raise RuntimeError("Authenticated far-field frequency request is invalid")
    axes = []
    for name, lower, upper, maximum in (("theta", 0, 180, 721), ("phi", -360, 360, 1441)):
        sampling = value.get(name, {})
        start, stop = float(sampling.get("start_deg", math.nan)), float(sampling.get("stop_deg", math.nan))
        points = int(sampling.get("points", 0))
        if not math.isfinite(start) or not math.isfinite(stop) or start < lower or stop > upper or stop <= start or not 2 <= points <= maximum or (name == "phi" and stop-start > 360):
            raise RuntimeError("Authenticated far-field " + name + " sampling is invalid")
        axes.append(np.linspace(start, stop, points))
    radius = float(value.get("radius_m", math.nan))
    center = np.asarray(value.get("center_mm", []), dtype=float)
    if not math.isfinite(radius) or not 1e-6 <= radius <= 1e6 or center.shape != (3,) or not np.all(np.isfinite(center)):
        raise RuntimeError("Authenticated far-field radius or phase center is invalid")
    samples = int(frequencies.size * axes[0].size * axes[1].size)
    if not 1 <= sample_limit <= 1000000 or samples > sample_limit:
        raise RuntimeError("Authenticated far-field request exceeds the output sample budget")
    return {"frequencies":frequencies,"theta":axes[0],"phi":axes[1],"radius":radius,"center":center,"shape":(int(frequencies.size),int(axes[0].size),int(axes[1].size))}

def finite_array(value, name, shape, complex_values=False, nonnegative=False, positive=False):
    array = np.asarray(value, dtype=complex if complex_values else float)
    if array.shape != shape or not np.all(np.isfinite(array)) or np.any(np.abs(array) > 1e300):
        raise RuntimeError(name + " has an invalid shape or non-finite values")
    if nonnegative and np.any(array < 0): raise RuntimeError(name + " contains negative values")
    if positive and np.any(array <= 0): raise RuntimeError(name + " must contain positive values")
    return array

def normalized_far_field(nf2ff, simulation_path, request, verbose, incident_voltage, reference_impedance):
    # Pulse FD dumps contain Fourier integrals, not unit-excitation phasors.
    # Establish an explicit one-watt incident wave with zero voltage phase.
    try:
        valid_reference = not isinstance(reference_impedance, bool) and isinstance(reference_impedance, (int, float)) and math.isfinite(reference_impedance) and reference_impedance > 0
    except OverflowError:
        valid_reference = False
    if not valid_reference:
        raise RuntimeError("NF2FF reference impedance must be finite and positive")
    frequency_shape = (request["shape"][0],)
    incident = finite_array(incident_voltage, "NF2FF incident spectrum", frequency_shape, complex_values=True)
    spectral_floor = max(float(np.max(np.abs(incident))) * np.finfo(float).eps, 1e-150)
    if np.any(np.abs(incident) <= spectral_floor):
        raise RuntimeError("NF2FF incident spectrum is missing or too small for normalization")
    with np.errstate(over="raise", invalid="raise", divide="raise"):
        try:
            amplitude_scale = math.sqrt(reference_impedance) * math.sqrt(2.0) / incident
            power_scale = np.abs(amplitude_scale)**2
        except FloatingPointError as error:
            raise RuntimeError("NF2FF incident normalization exceeds numeric range") from error
    if not np.all(np.isfinite(power_scale)) or np.any(power_scale <= 0):
        raise RuntimeError("NF2FF incident normalization exceeds numeric range")
    transformed = nf2ff.CalcNF2FF(
        sim_path=str(simulation_path), freq=request["frequencies"], theta=request["theta"], phi=request["phi"],
        radius=request["radius"], center=(request["center"] * 1e-3).tolist(),
        outfile=str(simulation_path / "spike-nf2ff.h5"), read_cached=False, verbose=verbose,
    )
    shape = request["shape"]
    returned_frequency = finite_array(transformed.freq, "NF2FF frequency", frequency_shape)
    if not np.allclose(returned_frequency, request["frequencies"], rtol=1e-6, atol=1e-3):
        raise RuntimeError("NF2FF returned a frequency grid that differs from the request")
    e_theta = finite_array(transformed.E_theta, "NF2FF E-theta", shape, complex_values=True)
    e_phi = finite_array(transformed.E_phi, "NF2FF E-phi", shape, complex_values=True)
    e_norm = finite_array(transformed.E_norm, "NF2FF E magnitude", shape, nonnegative=True)
    angular_power = finite_array(transformed.P_rad, "NF2FF angular radiated power", shape, nonnegative=True)
    total_power = finite_array(transformed.Prad, "NF2FF total radiated power", frequency_shape, positive=True)
    maximum_directivity = finite_array(transformed.Dmax, "NF2FF maximum directivity", frequency_shape, positive=True)
    with np.errstate(over="raise", invalid="raise", divide="raise"):
        try:
            e_theta = e_theta * amplitude_scale.reshape((-1, 1, 1))
            e_phi = e_phi * amplitude_scale.reshape((-1, 1, 1))
            e_norm = e_norm * np.abs(amplitude_scale).reshape((-1, 1, 1))
            # openEMS P_rad is local radial flux density, W/m^2; export
            # radiation intensity W/sr so angular integration yields watts.
            angular_power = angular_power * power_scale.reshape((-1, 1, 1)) * request["radius"]**2
            total_power = total_power * power_scale
        except FloatingPointError as error:
            raise RuntimeError("NF2FF normalized result exceeds numeric range") from error
    directivity = angular_power * (4 * math.pi) / total_power.reshape((-1, 1, 1))
    if not np.all(np.isfinite(directivity)) or np.any(directivity < 0):
        raise RuntimeError("NF2FF directivity normalization produced invalid values")
    # Report the maximum of our sampled, radius-corrected intensity. This does
    # not claim an unsampled spherical peak or rely on backend Dmax conventions.
    maximum_directivity = np.max(directivity, axis=(1, 2))
    flatten = lambda value: value.reshape(-1).tolist()
    return {
        "contract":"spike/openems-far-field-result/v1", "status":"computed", "validation_status":"not_validated",
        "normalization":{"kind":"incident_power", "incident_power_w":1.0,
                         "incident_voltage_phase_deg":0.0, "reference_impedance_ohm":reference_impedance, "phasor":"peak",
                         "source_spectrum":"single_sided_pulse_fourier_integral",
                         "frequency_sampling":"exact_port_reevaluation"},
        "frequencies_hz":request["frequencies"].tolist(), "theta_deg":request["theta"].tolist(), "phi_deg":request["phi"].tolist(),
        "radius_m":request["radius"], "center_mm":request["center"].tolist(), "shape":list(shape),
        "e_field_v_m":{
            "theta":{"real":flatten(np.real(e_theta)),"imag":flatten(np.imag(e_theta))},
            "phi":{"real":flatten(np.real(e_phi)),"imag":flatten(np.imag(e_phi))},
            "magnitude":flatten(e_norm),
        },
        "directivity":{"linear":flatten(directivity),"maximum_linear":maximum_directivity.tolist()},
        "radiated_power":{"angular_w":flatten(angular_power),"angular_units":"W/sr","total_w":total_power.tolist()},
        "validation":{
            "status":"not_validated",
            "established":["openems_execution_completed","nf2ff_output_shape_checked","finite_numeric_output_checked"],
            "required":["mesh_convergence","analytical_or_reference_fixture_comparison","measurement_or_trusted_solver_correlation"],
        },
    }

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--job", required=True)
    parser.add_argument("--setup-only", action="store_true")
    args = parser.parse_args()
    root = Path(args.job).resolve()
    if not isinstance(globals().get("SPIKE_JOB_SNAPSHOT"), str) or not isinstance(globals().get("SPIKE_GEOMETRY_SNAPSHOT"), str):
        raise RuntimeError("The openEMS adapter must be launched by SPIKE with authenticated input snapshots")
    geometry = json.loads(SPIKE_GEOMETRY_SNAPSHOT)
    job = json.loads(SPIKE_JOB_SNAPSHOT)
    run_context = job.get("run_context", {})
    if not all(isinstance(run_context.get(key), str) and run_context.get(key) for key in ("run_id", "job_id", "input_digest")):
        raise RuntimeError("The authenticated openEMS run context is missing")
    options = job.get("options", {})
    conductors, assembly = geometry["conductors"], geometry["assembly"]
    selected = set(geometry["selection"]["net_names"])
    stackup = assembly.get("stackup", [])
    elevations, dielectric_ranges, stack_bottom = layer_geometry(stackup)
    f_start = float(geometry["frequency"]["start_hz"])
    f_stop = float(geometry["frequency"]["stop_hz"])
    f0, fc = (f_start + f_stop) / 2, (f_stop - f_start) / 2
    analysis_options = job.get("analysis", {}).get("options", {})
    far_request = far_field_request(
        analysis_options.get("far_field") if isinstance(analysis_options, dict) else None,
        f_start, f_stop, int(options.get("max_far_field_samples", 250000)),
    )
    csx = ContinuousStructure()
    fdtd = openEMS(
        NrTS=int(options.get("max_timesteps", 10000000)),
        EndCriteria=float(options.get("end_criteria", 1e-5)),
        MaxTime=float(options.get("max_solver_time_s", 3600)),
    )
    fdtd.SetCSX(csx); fdtd.SetGaussExcite(f0, fc)
    fdtd.SetBoundaryCond(options.get("boundary_conditions", ["PML_8"] * 6))
    grid = csx.GetGrid(); grid.SetDeltaUnit(1e-3)
    xs, ys = [], []
    for group in (conductors.get("tracks", []), conductors.get("zones", []), conductors.get("pads", []), conductors.get("vias", [])):
        for item in group:
            if selected and net_of(item) not in selected: continue
            for key in ("start", "end", "at"):
                if key in item:
                    x, y = point(item[key]); xs.append(x); ys.append(y)
            for p in item.get("points", item.get("polygon", [])):
                x, y = point(p); xs.append(x); ys.append(y)
    if not xs: raise RuntimeError("No selected conductor geometry reached the openEMS adapter")
    # Full pad extents, not merely centers, must reach the dielectric/air bounds.
    for pad in conductors.get("pads", []):
        if selected and net_of(pad) not in selected: continue
        polygon = pad_polygon(pad)
        xs.extend(polygon[0]); ys.extend(polygon[1])
    bounds = [min(xs), max(xs), min(ys), max(ys)]
    eps_max = max([float(layer.get("epsilon_r", layer.get("epsilonR", 1)) or 1) for layer in stackup] + [1.0])
    wavelength_mm = C0 / f_stop / math.sqrt(eps_max) * 1000
    mesh_resolution = float(options.get("mesh_resolution_mm", max(min(wavelength_mm / 25, 2.0), 0.02)))
    air = float(options.get("air_padding_mm", min(max(wavelength_mm / 10, 5.0), 100.0)))
    x0, x1, y0, y1 = bounds[0]-air, bounds[1]+air, bounds[2]-air, bounds[3]+air
    z0, z1 = stack_bottom-air, air
    for layer, bottom, top in dielectric_ranges:
        epsilon = float(layer.get("epsilon_r", layer.get("epsilonR", 1)) or 1)
        loss = float(layer.get("loss_tangent", layer.get("lossTangent", 0)) or 0)
        kappa = 2 * math.pi * f0 * EPS0 * epsilon * loss
        material = csx.AddMaterial("dielectric_" + str(layer.get("name", "layer")).replace(".", "_"), epsilon=epsilon, kappa=kappa)
        material.AddBox([bounds[0], bounds[2], bottom], [bounds[1], bounds[3], top], priority=0)
    sheets = {}
    for name, z in elevations.items():
        source = next((layer for layer in stackup if layer.get("name") == name), {})
        thickness_m = max(float(source.get("thickness", source.get("thickness_mm", 0.035)) or 0.035), 1e-6) * 1e-3
        sheets[name] = csx.AddConductingSheet("copper_" + name.replace(".", "_"), conductivity=float(source.get("conductivity", 5.8e7) or 5.8e7), thickness=thickness_m)
    if not sheets: raise RuntimeError("No mapped copper layers reached the openEMS adapter")
    active_sheets = set()
    for track in conductors.get("tracks", []):
        if selected and net_of(track) not in selected: continue
        layer = str(track.get("layer", "F.Cu"))
        if layer not in sheets: raise RuntimeError("Unmapped track layer: " + layer)
        sheets[layer].AddPolygon(polygon_for_track(track), "z", elevations[layer], priority=10)
        active_sheets.add(layer)
    for zone in conductors.get("zones", []):
        if selected and net_of(zone) not in selected: continue
        source_points = zone.get("points", zone.get("polygon", []))
        if len(source_points) >= 3:
            layer = str(zone.get("layer", "F.Cu"))
            if layer not in sheets: raise RuntimeError("Unmapped zone layer: " + layer)
            sheets[layer].AddPolygon(polygon_coordinates(source_points), "z", elevations[layer], priority=8)
            active_sheets.add(layer)
    for pad in conductors.get("pads", []):
        if selected and net_of(pad) not in selected: continue
        pad_layers = pad.get("layers", [pad.get("layer", "F.Cu")])
        if not isinstance(pad_layers, list): pad_layers = [pad_layers]
        if "*.Cu" in pad_layers: pad_layers = list(sheets)
        for layer in pad_layers:
            if layer in sheets:
                sheets[layer].AddPolygon(pad_polygon(pad), "z", elevations[layer], priority=12)
                active_sheets.add(layer)
    via_material = csx.AddMaterial("plated_vias", kappa=5.8e7)
    for via in conductors.get("vias", []):
        if selected and net_of(via) not in selected: continue
        x, y = point(via.get("at", [0, 0])); layers = via.get("layers", ["F.Cu", "B.Cu"])
        top = elevations.get(layers[0], max(elevations.values())); bottom = elevations.get(layers[-1], min(elevations.values()))
        diameter = float(via.get("size", via.get("diameter", 0.6)) or 0.6); drill = float(via.get("drill", 0.3) or 0.3)
        plating = float(via.get("plating_thickness_mm", options.get("via_plating_thickness_mm", 0.025)) or 0.025)
        available_wall = max((diameter-drill)/2, 1e-6)
        via_material.AddCylindricalShell([x, y, bottom], [x, y, top], radius=drill/2 + min(plating, available_wall), shell_width=min(plating, available_wall), priority=15)
    for layer in active_sheets:
        fdtd.AddEdges2Grid(dirs="xy", properties=sheets[layer], metal_edge_res=max(mesh_resolution / 2, 0.001))
    dielectric_cells = int(options.get("dielectric_cells_per_layer", 3))
    dielectric_mesh = [
        value
        for _layer, bottom, top in dielectric_ranges
        for value in np.linspace(bottom, top, dielectric_cells + 1)
    ]
    grid.AddLine("x", [x0, x1] + xs); grid.AddLine("y", [y0, y1] + ys)
    grid.AddLine("z", [z0, z1] + list(elevations.values()) + dielectric_mesh)
    ports = []
    for index, port in enumerate(geometry["excitations"].get("ports", [])):
        ports.append(fdtd.AddLumpedPort(index+1, float(port.get("impedance_ohm", 50)), port["start"], port["stop"], str(port.get("direction", "z")), 1.0 if port.get("excite", False) else 0.0, priority=50, edges2grid="all"))
    grid.SmoothMeshLines("all", mesh_resolution, ratio=float(options.get("mesh_growth_ratio", 1.4)))
    pin_mesh_lines(grid, "z", list(elevations.values()) + dielectric_mesh)
    pin_mesh_lines(grid, "x", [float(value) for port in geometry["excitations"].get("ports", []) for value in (port["start"][0], port["stop"][0])])
    pin_mesh_lines(grid, "y", [float(value) for port in geometry["excitations"].get("ports", []) for value in (port["start"][1], port["stop"][1])])
    nf2ff = fdtd.CreateNF2FFBox("spike_nf2ff", frequency=far_request["frequencies"]) if far_request is not None else None
    output = root / "engine-output"; output.mkdir(exist_ok=True)
    csx.Write2XML(str(root / "engine-input" / "spike-openems.xml"))
    run_binding = {
        "run_id": run_context["run_id"],
        "job_id": run_context["job_id"],
        "input_digest": run_context["input_digest"],
        "frequency_start_hz": f_start,
        "frequency_stop_hz": f_stop,
        "frequency_points": int(geometry["frequency"].get("points", 101)),
        "mesh_resolution_mm": mesh_resolution,
        "max_timesteps": int(options.get("max_timesteps", 10000000)),
    }
    if args.setup_only:
        result = {"contract":"spike/external-result/v1","engine_id":"external.openems","status":"setup_completed","model_status":"approximate","artifacts":["engine-input/spike-openems.xml"],"mesh":{"resolution_mm":mesh_resolution},"run_binding":run_binding}
    else:
        fdtd.Run(str(output / "simulation"), cleanup=True, verbose=int(options.get("verbosity", 2)), numThreads=int(options.get("threads", 0)))
        frequencies = np.linspace(f_start, f_stop, int(geometry["frequency"].get("points", 101)))
        for port in ports: port.CalcPort(str(output / "simulation"), frequencies, ref_impedance=float(options.get("reference_impedance_ohm", 50)))
        excited = next(i for i,p in enumerate(geometry["excitations"].get("ports", [])) if p.get("excite", False))
        incident = np.asarray(ports[excited].uf_inc)
        if incident.shape != frequencies.shape or not np.all(np.isfinite(incident)):
            raise RuntimeError("Excited-port incident voltage is missing or non-finite")
        floor = max(np.finfo(float).eps * max(float(np.max(np.abs(incident))), 1.0), 1e-300)
        if np.any(np.abs(incident) <= floor):
            raise RuntimeError("Excited-port incident voltage is too small for stable S-parameter normalization")
        columns = {}
        for index, port in enumerate(ports):
            reflected = np.asarray(port.uf_ref)
            if reflected.shape != frequencies.shape or not np.all(np.isfinite(reflected)):
                raise RuntimeError("Port reflected voltage is missing or non-finite")
            values = reflected / incident
            if not np.all(np.isfinite(values)):
                raise RuntimeError("S-parameter normalization produced a non-finite value")
            columns[f"s{index+1}{excited+1}"] = {"real":np.real(values).tolist(),"imag":np.imag(values).tolist()}
        result = {"contract":"spike/external-result/v1","engine_id":"external.openems","status":"completed","model_status":"unvalidated" if far_request is not None else "approximate","frequency_hz":frequencies.tolist(),"s_parameters":columns,"artifacts":["engine-input/spike-openems.xml","engine-output/simulation"],"mesh":{"resolution_mm":mesh_resolution},"run_binding":run_binding}
        if far_request is not None:
            reference_impedance = float(options.get("reference_impedance_ohm", 50))
            ports[excited].CalcPort(str(output / "simulation"), far_request["frequencies"], ref_impedance=reference_impedance)
            result["far_field"] = normalized_far_field(nf2ff, output / "simulation", far_request, int(options.get("verbosity", 2)), ports[excited].uf_inc, reference_impedance)
    (output / "normalized-result.json").write_text(json.dumps(result, allow_nan=False), encoding="utf-8")
    print(json.dumps({"status": result["status"], "result": str(output / "normalized-result.json")}, allow_nan=False))

if __name__ == "__main__": main()
'''.replace("__SPIKE_PAD_POLYGON_SOURCE__", PAD_POLYGON_SOURCE)
